services:
  splunk:
    build: ./splunk 
    container_name: crslsdrnp-cntnr-splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunkpass
      - TZ=America/Sao_Paulo
    ports:
      - '8001:8000'
      - '8088:8088'
    networks:
      - project_network

  database:
    image: postgres:13
    container_name: database-postgres-13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatproject
      - TZ=America/Sao_Paulo
    ports:
      - '5435:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - project_network

  api:
    image: api-nodejs-20
    build: ./api
    container_name: api-node-20
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chatproject
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - '3001:3001'
    depends_on:
      - database
    networks:
      - project_network

  ui:
    image: vite-reactjs-node-20
    build: ./frontend
    container_name: ui-node-20
    ports:
      - '3002:3002'
    depends_on:
      - api
    networks:
      - project_network

networks:
  project_network:
    driver: bridge