services:
  database:
    image: postgres:13
    container_name: database-postgres-13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatproject
    ports:
      - '5435:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - project_network

networks:
  project_network:
    driver: bridge